# docker-compose.yml
version: '3'
services:
  database:
    image: "postgres" # use latest official postgres version
    ports: 
      - "5432:5432"
    env_file: 
      - ./config/database.env
    volumes:
      - database-data:/var/lib/postgresql/data/ # persist data even if container shuts down
  app: 
    build: ./app
    env_file: 
      - ./config/app.env
    ports: 
      - "80:5000" #Link local port 80 to container port 5000docker colume
    volumes:
     - "./app:/app" #Mount the local app directory into the container

    
volumes:
  database-data: # named volumes can be managed easier using docker-compose